### ISSUE TITLE
Incorrect Nreps

### ISSUE THREAD

**Issue by dschaeffer17** [uclahedp/uclahedp#10]
Number of reps per position (Nreps) is currently derived by looking at the number of unique positions per axis saved.  In odd cases where the position may shift slightly (by >0.1 cm) when it's not supposed to, this is now counted as two unique positions, which yields an incorrect Nreps param and throws off the whole data grid.  A better general approach would be to use the Nx, Ny, and Nz params in the HDF file and compute Nreps = total shots/(Nx*Ny*Nz).

**Comment by pheuer** [comment]
This is exists because bapsflib does not currently allow access to the metadata about controls, so we don't have access to Nxyz, dxyz, etc. I have submitted an issue to that package to have this added in the next release, which can be found [here](https://github.com/BaPSF/bapsflib/issues/32).

The current method works well if the "precision" keyword argument to postools.gridShotIndList is set appropriately in process.bdot (~line 113). This is the precision to which the positions are rounded before gridding, and is set to 0.1 cm by default, hence the error you observed. As a short-term fix, you could try changing that value to .15 cm or something and see if that grids correctly.

**Comment by dschaeffer17** [comment]
Is it possible to directly extract the metadata from the H5 files?

**Comment by pheuer** [comment]
Yes: I now know how to do this with bapsflib (and have hardcoded it for the drives bapsflib does not yet support), so this is now an option  for bdot.py. The code now supports two modes for both generating grid axes and locating shots on the grid. These are called "strict" and "fuzzy" axes and gridding for now. The strict versions use the nominal grid parameters to construct the axes, and place shots on the grid by assuming an X->Y->Z motion order and no missed shots/locations. The fuzzy version (previously the only option) semi-intelligently recognizes the axes and matches shots to the grid. It accomplishes this by rounding the recorded positions to within some number (the "grid_precision" keyword) and then looking for matches. You can mix and match these options by setting the "strict_axes" and "strict_grid" keywords in bdot.py.

Note that the fuzzy version is generally superior, because it will correctly handle situations where probes do not move to the desired location. The strict versions have very little fault tolerance.
