### ISSUE TITLE
Add options for where in raw signal to calculate bias voltage offset

### ISSUE THREAD

**Issue by dschaeffer17** [uclahedp/uclahedp#6]
Currently, the bdot.py routine applies a detrend() operation to the entire raw voltage signal.  This is likely skewing current processed bdot signals, since we're really only interested in the initial bias voltage.

I'd recommend adding (optional) input variables that specify the start index and number of indices over which to average (or detrend, though averaging should be fine) the raw signal, and then subtract this value from the whole signal.

By default, the start index would be 0, and maybe ~10000 indices long.  Whatever the values are (default or input) should be printed.  If there's a timing diode, it would be convenient to also print the selected values in time units.

**Comment by pheuer** [comment]
Changed in latest update (9daa66c6ab7fa07771374b26c13b94db5d6e68be). A printout with both indices and times based on the timing diode has been added.

The default range is set to (0,100), since this is about all that is available for the HRR experiments with our CAEN digitizer. If you have more points, setting it to 10000 should be supported.
